### ISSUE TITLE
SignatureDoesNotMatch with ZF 2.2.5 due to Date format

### ISSUE THREAD

**Issue by lucidix** [zendframework/ZendService_Amazon#41] opened 2013-11-03 21:32 UTC
The date format for Zend\Http\Client seems to have changed from ZF 2.2.4 to ZF 2.2.5. Previously, the date was formatted as "Sun, 03 Nov 2013 15:07:45 -0500". However, starting with ZF 2.2.5 the format is "Sun, 03 Nov 2013 20:07:45 GMT". (I couldn't yet nail down exactly why, but was able to "resolve" it by replacing ZF 2.2.5's \Zend\Http directory with ZF 2.2.4's.).

This impacts the AWS Request Signature due to the mismatch with how `\ZendService\Amazon\S3\S3::getRequestDate()` generates the signature.

I've patched that method using

``` php
$date = new \DateTime('now', new \DateTimeZone('GMT'));
return $date->format('D, d M Y H:i:s \G\M\T');
```

which matches how `\Zend\Http\Header\AbstractDate::setDate()` works.

Thanks!

**Comment by ddxor** [comment] 2015-05-12 11:19
This affects me

**Comment by matwright** [comment] 2015-05-12 11:21
@ddxor you can use https://github.com/matwright/ZendService_Amazon/tree/hotfix/signature-date-issue 
note the travis fails are not specific to this PR

**Comment by matwright** [comment] 2015-05-12 12:46
@ddxor  The latest version of ZF2 is 2.4.2 reverting back to 2.2.4 isn't a great idea.

@Maks3w Is this issue due to be resolved in another PR or future release ?

**Comment by NeilSmith100** [comment] 2016-08-11 12:06
This will affect users where their server settings are UTC instead of GMT/BST

Date Default timezone	UTC
date.timezone	UTC UTC

Set in index.php : 
date_default_timezone_set('UTC');

As per @lucidix  comment above : In ZendService\Amazon\S3\S3::getRequestDate returns timezone type = 3 (the server default setting chosen)

```
DateTime Object
(
    [date] => 2016-08-11 11:31:00.000000
    [timezone_type] => 3
    [timezone] => UTC
)
```

Zend\HTTP\Header\AbstractDate specfically uses GMT in date format, and returns timezone type = 2 because this is explicitly used in setDate()

`$date = new DateTime($date, new DateTimeZone('GMT'));`

```
DateTime Object(
    [date] => 2016-08-11 11:31:00.000000
    [timezone_type] => 2
    [timezone] => GMT
  )
```

I think the defect is in ZendService AbstrctAmazon, because even if we set timezone by passing a configured Date object into 'setRequestDate', our output format is Thu, 11 Aug 2016 12:05:44 +0000 which has timezone '+0000' not 'GMT'

**Comment by NeilSmith100** [comment] 2016-08-11 12:20
[ZendServiceS3SignatureDate.txt](https://github.com/zendframework/ZendService_Amazon/files/413138/ZendServiceS3SignatureDate.txt)

**Comment by demiankatz** [comment] 2017-03-07 13:55
@Xerkus, as we discussed on IRC yesterday, I have confirmed that this issue still stands, and also that PR #49 fixes the problem. Here's what I did:

1.) I created a test script based on the documentation:

<pre>
$s3 = new ZendService\Amazon\S3\S3($my_aws_key, $my_aws_secret_key);
$s3->createBucket("my-own-bucket");
$s3->putObject("my-own-bucket/myobject", "somedata");
echo $s3->getObject("my-own-bucket/myobject");
</pre>

(Note that there is an error in the documentation -- its examples refer to the `ZendService\Amazon\S3\S3` class as simply `ZendService\Amazon\S3`).

2.) I ran my test script against master, and authentication failed.

3.) I merged #49 into master and ran my test script again; it succeeded.

Recommendation: merge #49.

**Closed** 2017-03-07 18:31 UTC

**Comment by NeilSmith100** [comment] 2017-03-08 10:09
Thanks all - appreciate the simple fix.
Do we know if this is in release branch ?
(if not, when ?)

**Comment by Xerkus** [comment] 2017-03-09 17:45
@NeilSmith100 in couple days in 2.1.0
